-- 제약조건  변경

-- 게시판
ALTER TABLE board
DROP CONSTRAINT BRD_MNO_FK;

ALTER TABLE board
ADD CONSTRAINT BRD_MNO_FK FOREIGN KEY(bmno) REFERENCES member(mno)
ON DELETE CASCADE;

ALTER TABLE fileinfo
DROP CONSTRAINT FI_BNO_FK;

-- 방명록
ALTER TABLE guestboard
DROP CONSTRAINT GBRD_WRITER_FK;

ALTER TABLE guestboard
ADD CONSTRAINT GBRD_WRITER_FK FOREIGN KEY(writer) REFERENCES member(mno)
ON DELETE CASCADE;

-- 댓글 게시판
ALTER TABLE reboard
DROP CONSTRAINT RBRD_MNO_FK;

ALTER TABLE reboard
ADD CONSTRAINT RBRD_MNO_FK FOREIGN KEY(rbmno) REFERENCES member(mno)
ON DELETE CASCADE;

-- 설문조사
ALTER TABLE survey
DROP CONSTRAINT SV_MNO_FK;

ALTER TABLE survey
DROP CONSTRAINT SV_MNO_NN;
